export const REGISTER_CAT = "REGISTER_CAT";
export const CAT_ADOPTED = "CAT_ADOPTED";
export const CAT_STERILISED = "CAT_STERILISED";
export const CAT_VACCINATED = "CAT_VACCINATED";
export const INITIALIZE_APP = "INITIALIZE_APP";
