export const REGISTER_CAT = "REGISTER_CAT";
export const CAT_IN_ADOPTION = "CAT_IN_ADOPTION";
export const CAT_STERILISED = "CAT_STERILISED";
export const CAT_VACCINATED = "CAT_VACCINATED";
export const INITIALIZE_APP = "INITIALIZE_APP";
